server:
  port: 9090


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/citizen
    username: root
    password: Sinha@12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: CITIZEN-SERVICE


